import { Link } from "react-router-dom";

export default function Footer() {
  const year = new Date().getFullYear();

  return (
    <footer className="site-footer">
      <div className="site-footer__inner">
        <div className="site-footer__security">
          <span className="site-footer__lock" aria-hidden="true">🔒</span>
          <p>
            <strong>Your data is protected.</strong> Everything you enter is
            sent over an encrypted connection, passwords are stored only as
            irreversible hashes, and your health details are never sold or
            shared with advertisers, insurers, or employers. Only you can see
            your profiles and saved trials.
          </p>
        </div>

        <nav className="site-footer__links" aria-label="Legal and information">
          <Link to="/privacy">Privacy Policy</Link>
          <Link to="/terms">Terms of Use</Link>
          <Link to="/what-is-a-clinical-trial">What is a trial?</Link>
          <Link to="/why-participate">Why participate</Link>
          <a
            href="https://clinicaltrials.gov"
            target="_blank"
            rel="noopener noreferrer"
          >
            ClinicalTrials.gov ↗
          </a>
        </nav>

        <p className="site-footer__disclaimer">
          TrialFinder is an informational tool and does not provide medical
          advice, diagnosis, or treatment. Results are generated by software and
          may be incomplete or out of date. Always confirm eligibility with the
          trial&apos;s study team and discuss any decision with a qualified
          healthcare provider. Trial data is sourced from ClinicalTrials.gov,
          operated by the U.S. National Library of Medicine. TrialFinder is not
          a HIPAA covered entity.
        </p>

        <p className="site-footer__copy">
          © {year} TrialFinder. Built for patients and their families.
        </p>
      </div>
    </footer>
  );
}
