import { Link } from "react-router-dom";

export default function Terms() {
  return (
    <article className="article">
      <header className="article__head">
        <p className="article__eyebrow">Legal</p>
        <h1 className="article__title">Terms of Use</h1>
        <p className="article__lede">
          Please read these terms before using TrialFinder. They explain what
          this service is, and just as importantly, what it is not.
        </p>
        <p className="article__meta">Last updated: August 2026</p>
      </header>

      <section className="article__section">
        <h2>Not medical advice</h2>
        <p>
          TrialFinder is an informational search tool. It does not practice
          medicine, does not diagnose, and does not recommend treatment. The
          matches and explanations it produces are generated by software,
          including an AI model, and may be incomplete or wrong.
        </p>
        <p>
          Never make a treatment decision based on this site alone. Always
          consult a qualified healthcare provider, and confirm any trial&apos;s
          eligibility criteria directly with that trial&apos;s study team before
          acting on it.
        </p>
      </section>

      <section className="article__section">
        <h2>Where the information comes from</h2>
        <p>
          Trial listings come from ClinicalTrials.gov, a registry operated by
          the U.S. National Library of Medicine. We do not control that data and
          cannot guarantee it is current or accurate. Trials close, criteria
          change, and sites stop enrolling, sometimes before the registry is
          updated.
        </p>
        <p>
          Supplementary details such as site reputation and drug background are
          assembled from public web sources and may contain errors. Treat every
          result as a starting point for a conversation with your doctor, not as
          a verified fact.
        </p>
      </section>

      <section className="article__section">
        <h2>No relationship is created</h2>
        <p>
          Using TrialFinder does not create a doctor-patient relationship, and
          it does not enroll you in anything. Only a trial&apos;s own study team
          can screen and enroll you.
        </p>
      </section>

      <section className="article__section">
        <h2>Acceptable use</h2>
        <p>By using this service, you agree not to:</p>
        <ul className="reasons">
          <li>Scrape, crawl, or bulk-download data from the service.</li>
          <li>Use automated scripts or bots against the API.</li>
          <li>Attempt to access another user&apos;s account or data.</li>
          <li>Probe, scan, or test the security of the service without permission.</li>
          <li>Submit deliberately false information, or another person&apos;s health information without their consent.</li>
        </ul>
        <p>
          We rate limit requests and block automated clients to keep the service
          available for patients. Accounts that abuse the service may be
          suspended.
        </p>
      </section>

      <section className="article__section">
        <h2>No warranty and limitation of liability</h2>
        <p>
          This service is provided &ldquo;as is,&rdquo; without warranties of
          any kind, express or implied, including fitness for a particular
          purpose. To the maximum extent permitted by law, we are not liable for
          any damages arising from your use of the service or from any decision
          made in reliance on it.
        </p>
      </section>

      <section className="article__section">
        <h2>Changes</h2>
        <p>
          We may update these terms as the service evolves. Continued use after
          an update means you accept the revised terms.
        </p>
      </section>

      <div className="article__cta">
        <Link to="/privacy" className="btn btn--ghost">
          Privacy Policy
        </Link>
        <Link to="/" className="btn btn--primary">
          Find trials
        </Link>
      </div>
    </article>
  );
}
